version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
      - 24224:24224
    expose:
      - "24224"
    depends_on:
      - db
    networks:
      mynetwork:
        ipv4_address: 172.16.1.10
  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alesha2002
      POSTGRES_DB: frame
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432
    networks:
      mynetwork:
        ipv4_address: 172.16.1.20
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
        - subnet: 2001:3984:3989::/64