
services:
  db:
    container_name: db_frame_postgres
    image: postgres:16
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - .postgres:/var/lib/postgres/data
    ports:
      - 5433:5433
    restart: always
  app:
    container_name: frame-app
    build: ./
    volumes:
      - .:/app
    ports:
      - ${APP_HOST_PORT}:7000
    env_file:
      - .env
    depends_on:
      - db
    command: "/bin/sh ./app.sh"

