version: "3"

services:
  web:
    build: .
    command: sh -c "uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
  db:
    restart: always
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: alesha2002
      POSTGRES_DB: frame
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432