"""One to One

Revision ID: 060d38e5ea21
Revises: ac6721153de0
Create Date: 2024-07-19 21:10:00.960116

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060d38e5ea21'
down_revision: Union[str, None] = 'ac6721153de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_film_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'film_id')
    op.alter_column('films', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('films', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('categories', sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('categories_film_id_fkey', 'categories', 'films', ['film_id'], ['id'])
    # ### end Alembic commands ###
