"""One to One v5

Revision ID: 9728be306240
Revises: 5431664d1be8
Create Date: 2024-07-19 21:59:24.366568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9728be306240'
down_revision: Union[str, None] = '5431664d1be8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_film_id_fkey', 'categories', type_='foreignkey')
    op.drop_column('categories', 'film_id')
    op.add_column('films', sa.Column('category_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'films', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'films', type_='foreignkey')
    op.drop_column('films', 'category_id')
    op.add_column('categories', sa.Column('film_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('categories_film_id_fkey', 'categories', 'films', ['film_id'], ['id'])
    # ### end Alembic commands ###
