"""without model category

Revision ID: b4ef7c571056
Revises: a03c47f559fc
Create Date: 2024-07-27 01:02:26.077499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ef7c571056'
down_revision: Union[str, None] = 'a03c47f559fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'category_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
