"""One to One v2

Revision ID: cef9046ace80
Revises: 060d38e5ea21
Create Date: 2024-07-19 21:13:09.920357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef9046ace80'
down_revision: Union[str, None] = '060d38e5ea21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('film_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categories', 'films', ['film_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_column('categories', 'film_id')
    # ### end Alembic commands ###
