"""category str added

Revision ID: f2859d042ca6
Revises: b4ef7c571056
Create Date: 2024-07-27 01:07:25.175155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2859d042ca6'
down_revision: Union[str, None] = 'b4ef7c571056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('category', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'category')
    # ### end Alembic commands ###
